site_name: Dataloop Support
# site_url:
repo_url: https://github.com/dataloop/dataloop-support
site_description: Support and Help Documentation for Dataloop.IO
site_author: support@dataloop.io
copyright: © Dataloop 2017
# google_analytics: [ ]
remote_branch: gh-pages
# pages:
#   - Home: index.md
#   - Setup and Configuration: setup.md
#   - Integrations: integrations.md
#   - Troubleshooting: foo.md
theme: material
extra:
  logo: 'img/touchicon-x120.png'
  palette:
    primary: 'orange'
    accent: 'teal'
  social:
    - type: 'github'
      link: 'https://github.com/dataloop'
    - type: 'twitter'
      link: 'https://twitter.com/outlyerapp'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

